name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule: 
    - cron: "0 15 * * *"

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - run: npm install
    - run: npm test
